language: ruby
rvm:
  - 2.2.5

sudo: false
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

script:
  - cookstyle ./cookbooks/
  - foodcritic ./cookbooks/
  - rubocop ./plugins/
