---
driver:
  name: vagrant
  synced_folders:
    - ['test/integration/fixtures/docroot/', '/srv/matomo/']

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[matomo::default]
    attributes:
